// Creates the DEMO farm's users through the real Auth admin API (local stack only) and prints SQL
// that gives them profiles and roles in the demo farm. Usage: node demo-users.mjs <gatewayUrl> <serviceKey>
// The service key is the locally generated dev key from .local/secrets.env; it never leaves the machine.
const [, , base, serviceKey] = process.argv;
if (!base || !serviceKey) {
  console.error('usage: demo-users.mjs <gatewayUrl> <serviceKey>');
  process.exit(2);
}

export const DEMO_PASSWORD = 'demo-password-123';
const USERS = [
  { email: 'demo.admin@demo.local', name: 'مدير النظام (تجريبي)', roles: [['system_admin', null]] },
  { email: 'demo.ops@demo.local', name: 'مدير العمليات (تجريبي)', roles: [['operations_manager', null]] },
  { email: 'demo.agri.manager@demo.local', name: 'مدير الزراعة (تجريبي)', roles: [['department_manager', 'agriculture']] },
  { email: 'demo.supervisor@demo.local', name: 'مشرف ميداني (تجريبي)', roles: [['supervisor', 'agriculture']] },
  { email: 'demo.supervisor2@demo.local', name: 'مشرف ثانٍ (تجريبي)', roles: [['supervisor', 'agriculture']] },
  { email: 'demo.maint.manager@demo.local', name: 'مدير الصيانة (تجريبي)', roles: [['maintenance_manager', 'maintenance'], ['department_manager', 'maintenance']] },
  { email: 'demo.technician@demo.local', name: 'فني صيانة (تجريبي)', roles: [['maintenance_technician', 'maintenance']] },
  { email: 'demo.warehouse@demo.local', name: 'أمين مستودع (تجريبي)', roles: [['warehouse_user', 'main_warehouse']] },
  { email: 'demo.qa@demo.local', name: 'ضمان الجودة (تجريبي)', roles: [['qa_user', 'qa']] },
  { email: 'demo.exec@demo.local', name: 'مشاهد إداري (تجريبي)', roles: [['executive_viewer', null]] },
];

const headers = { apikey: serviceKey, authorization: `Bearer ${serviceKey}`, 'content-type': 'application/json' };

async function ensureUser(email) {
  const res = await fetch(`${base}/auth/v1/admin/users`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ email, password: DEMO_PASSWORD, email_confirm: true }),
  });
  if (res.ok) return (await res.json()).id;
  const list = await fetch(`${base}/auth/v1/admin/users?per_page=1000`, { headers });
  const users = (await list.json()).users ?? [];
  const found = users.find((u) => u.email === email);
  if (!found) throw new Error(`could not create ${email}: ${res.status} ${await res.text()}`);
  return found.id;
}

const q = (s) => (s === null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const out = ["-- generated by scripts/demo-users.mjs (demo farm only)", "do $$ declare f uuid := (select id from public.farms where code = 'DEMO' and is_demo); begin"];
for (const u of USERS) {
  const id = await ensureUser(u.email);
  out.push(`insert into public.user_profiles (id, farm_id, full_name) values (${q(id)}, f, ${q(u.name)}) on conflict (id) do nothing;`);
  for (const [role, dept] of u.roles) {
    out.push(
      `insert into public.user_roles (farm_id, user_id, role_id, department_id, valid_from)
       select f, ${q(id)}, (select id from public.roles where farm_id = f and code = ${q(role)}),
              ${dept ? `(select id from public.departments where farm_id = f and code = ${q(dept)})` : 'null'}, now() - interval '1 day'
        where not exists (select 1 from public.user_roles where user_id = ${q(id)} and role_id = (select id from public.roles where farm_id = f and code = ${q(role)}) and voided_at is null);`,
    );
  }
}
out.push('end $$;');
console.log(out.join('\n'));
